-- Usuarios Vacation System — 212 colaboradores
-- primernombre.primerapellido / contraseña: 54321

insert into public.usuarios (id, nombre, usuario, pass, rol, cia_id) values
  (gen_random_uuid(), 'Administrador', 'admin', 'glp2024', 'admin', null),
  (gen_random_uuid(), 'Personal RRHH', 'personal', 'glp123', 'personal', null),
  (gen_random_uuid(), 'JOSUE ENOC ORTEGA', 'josue.ortega', '54321', 'personal', null),
  (gen_random_uuid(), 'JUAN GABRIEL DEQUIA MAJORE', 'juan.dequia', '54321', 'personal', null),
  (gen_random_uuid(), 'KEVIN NOEL HERRERA', 'kevin.herrera', '54321', 'personal', null),
  (gen_random_uuid(), 'VICTOR SAMUDIO', 'victor.samudio', '54321', 'personal', null),
  (gen_random_uuid(), 'CARLOS RODRIGUEZ', 'carlos.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'JORGE VERGARA', 'jorge.vergara', '54321', 'personal', null),
  (gen_random_uuid(), 'MARCOS RODRIGUEZ', 'marcos.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'LEXY LARA', 'lexy.lara', '54321', 'personal', null),
  (gen_random_uuid(), 'NATIVIDAD TENORIO', 'natividad.tenorio', '54321', 'personal', null),
  (gen_random_uuid(), 'RICARDO TORRES', 'ricardo.torres', '54321', 'personal', null),
  (gen_random_uuid(), 'LUIS RAMIREZ', 'luis.ramirez', '54321', 'personal', null),
  (gen_random_uuid(), 'JESUS BLADIMIR MORELOS', 'jesus.morelos', '54321', 'personal', null),
  (gen_random_uuid(), 'ALEXANDER JAVIER MUÑOZ MUÑOZ', 'alexander.munoz', '54321', 'personal', null),
  (gen_random_uuid(), 'GABRIEL OBED CEDEÑO PEREZ', 'gabriel.cedeno', '54321', 'personal', null),
  (gen_random_uuid(), 'JENNIFER DANIELA ARANDA', 'jennifer.aranda', '54321', 'personal', null),
  (gen_random_uuid(), 'MARICELLE  HAYDEE DE SEDAS', 'maricelle.haydeede', '54321', 'personal', null),
  (gen_random_uuid(), 'OGUEN ESTEBAN CRUZ ACOSTA', 'oguen.cruz', '54321', 'personal', null),
  (gen_random_uuid(), 'RAUL GARCIA', 'raul.garcia', '54321', 'personal', null),
  (gen_random_uuid(), 'SOLYMAR SANTANA', 'solymar.santana', '54321', 'personal', null),
  (gen_random_uuid(), 'YASSIEL EDITH SOLIS AMAYA', 'yassiel.solis', '54321', 'personal', null),
  (gen_random_uuid(), 'YESENIA LINETH  CORTEZ RIOS', 'yesenia.cortez', '54321', 'personal', null),
  (gen_random_uuid(), 'MARISSEL ROCIO HERNANDEZ CUBILLA', 'marissel.hernandez', '54321', 'personal', null),
  (gen_random_uuid(), 'ROXANA MOK GONZALEZ', 'roxana.mok', '54321', 'personal', null),
  (gen_random_uuid(), 'VALERIE RACHELLE SANTAMARIA', 'valerie.santamaria', '54321', 'personal', null),
  (gen_random_uuid(), 'ANDRES ANTONIO ARAUZ', 'andres.arauz', '54321', 'personal', null),
  (gen_random_uuid(), 'CRISTEL BARRIA', 'cristel.barria', '54321', 'personal', null),
  (gen_random_uuid(), 'FLOR DEL CARMEN UREÑA', 'flor.urena', '54321', 'personal', null),
  (gen_random_uuid(), 'FULVIA PEÑA CHACON', 'fulvia.pena', '54321', 'personal', null),
  (gen_random_uuid(), 'GAD AHIEZER SANCHEZ FIGUEROA', 'gad.sanchez', '54321', 'personal', null),
  (gen_random_uuid(), 'GIOVANNA RAQUEL VEGA MC KINNON', 'giovanna.vega', '54321', 'personal', null),
  (gen_random_uuid(), 'ISACK ERBACIO ROMERO GOMEZ', 'isack.romero', '54321', 'personal', null),
  (gen_random_uuid(), 'JUAN JOSE GONZALEZ OSSA', 'juan.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'DANIELA GONZALEZ', 'daniela.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'GISELLE JELENNY TREJOS', 'giselle.trejos', '54321', 'personal', null),
  (gen_random_uuid(), 'MELISSA BETHANCOURT', 'melissa.bethancourt', '54321', 'personal', null),
  (gen_random_uuid(), 'GLARISBETH AGUILAR', 'glarisbeth.aguilar', '54321', 'personal', null),
  (gen_random_uuid(), 'ALEJANDRO CARRION ESCOBAR', 'alejandro.carrion', '54321', 'personal', null),
  (gen_random_uuid(), 'ANA MARIA BEDOYA  BETHANCOURT', 'ana.bedoya', '54321', 'personal', null),
  (gen_random_uuid(), 'HEIDY CORTES', 'heidy.cortes', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSE ALBERTO MONTENEGRO', 'jose.montenegro', '54321', 'personal', null),
  (gen_random_uuid(), 'NILDA ROSA RODRIGUEZ  FLORES', 'nilda.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'VICTOR  JOEL VERGARA', 'victor.joel', '54321', 'personal', null),
  (gen_random_uuid(), 'YARICHELL DEL CARMEN RANKIN DE GRACIA', 'yarichell.carmen', '54321', 'personal', null),
  (gen_random_uuid(), 'DENIS DEL CARMEN TEJADA POVEDA', 'denis.carmen', '54321', 'personal', null),
  (gen_random_uuid(), 'STEFANIE ZAMORA', 'stefanie.zamora', '54321', 'personal', null),
  (gen_random_uuid(), 'EDWIN GONZALEZ', 'edwin.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'JUAN PABLO TACK HERNMAN', 'juan.tack', '54321', 'personal', null),
  (gen_random_uuid(), 'ALEXIS GUSMAN NAVARRO', 'alexis.gusman', '54321', 'personal', null),
  (gen_random_uuid(), 'CARLOS EDUARDO OBALDIA RODRIGUEZ', 'carlos.obaldia', '54321', 'personal', null),
  (gen_random_uuid(), 'EDGAR EMILIO QUINTANA DOMINGUEZ', 'edgar.quintana', '54321', 'personal', null),
  (gen_random_uuid(), 'JANELIS SUSSETH GOMEZ GOMEZ', 'janelis.gomez', '54321', 'personal', null),
  (gen_random_uuid(), 'ALFONZO GONZALEZ', 'alfonzo.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'STEFHANY HERRERA', 'stefhany.herrera', '54321', 'personal', null),
  (gen_random_uuid(), 'KRISCYA NAKYSHA QUINLAN OMBLER', 'kriscya.quinlan', '54321', 'personal', null),
  (gen_random_uuid(), 'SERAFIN AGUILAR MENDOZA', 'serafin.aguilar', '54321', 'personal', null),
  (gen_random_uuid(), 'LUZDARY VALERA MATHEUS', 'luzdary.valera', '54321', 'personal', null),
  (gen_random_uuid(), 'CRISTINA JULIO', 'cristina.julio', '54321', 'personal', null),
  (gen_random_uuid(), 'DARYELIS DARELIS RODRIGUEZ', 'daryelis.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'INCAMALICH NIETO GILL', 'incamalich.gill', '54321', 'personal', null),
  (gen_random_uuid(), 'ELSY ROMERO', 'elsy.romero', '54321', 'personal', null),
  (gen_random_uuid(), 'ESTEFANY CECILIA TAPIA', 'estefany.tapia', '54321', 'personal', null),
  (gen_random_uuid(), 'ISABELLA GORMAZ', 'isabella.gormaz', '54321', 'personal', null),
  (gen_random_uuid(), 'FREDDY ARAUZ', 'freddy.arauz', '54321', 'personal', null),
  (gen_random_uuid(), 'JESUS ADIEL PINEDA URRIOLA', 'jesus.pineda', '54321', 'personal', null),
  (gen_random_uuid(), 'JHOANA DENISE SANCHEZ', 'jhoana.sanchez', '54321', 'personal', null),
  (gen_random_uuid(), 'JORGE SERRANO', 'jorge.serrano', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSE RAUL SOSSA', 'jose.sossa', '54321', 'personal', null),
  (gen_random_uuid(), 'JULISSA GONZALEZ', 'julissa.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'KATHERINE RIVERA', 'katherine.rivera', '54321', 'personal', null),
  (gen_random_uuid(), 'FRANKLIN CAMPOS', 'franklin.campos', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSS EMERSON PÉREZ QUINN', 'joss.perez', '54321', 'personal', null),
  (gen_random_uuid(), 'LEYDIS VALDES', 'leydis.valdes', '54321', 'personal', null),
  (gen_random_uuid(), 'MARCO ALEXANDER RIVERA', 'marco.rivera', '54321', 'personal', null),
  (gen_random_uuid(), 'NAYELIS YAMILETH MEJIA', 'nayelis.mejia', '54321', 'personal', null),
  (gen_random_uuid(), 'NESTOR OCTAVIO CAMAÑO', 'nestor.camano', '54321', 'personal', null),
  (gen_random_uuid(), 'ROBERTO PINEDA', 'roberto.pineda', '54321', 'personal', null),
  (gen_random_uuid(), 'SOLEDAD DEL CARMEN  GONZALEZ CASTILLO', 'soledad.carmen', '54321', 'personal', null),
  (gen_random_uuid(), 'OSIRIS KARMILLA NIÑO', 'osiris.nino', '54321', 'personal', null),
  (gen_random_uuid(), 'ADRIAN ALTAMIRANDA PIMENTEL', 'adrian.altamiranda', '54321', 'personal', null),
  (gen_random_uuid(), 'ADRIANA BEATRIZ NAVA', 'adriana.nava', '54321', 'personal', null),
  (gen_random_uuid(), 'AFRODITA ANGELKOS VANEGAS', 'afrodita.vanegas', '54321', 'personal', null),
  (gen_random_uuid(), 'AMARILIS MARTINEZ', 'amarilis.martinez', '54321', 'personal', null),
  (gen_random_uuid(), 'LUIS CARLOS PUGA', 'luis.puga', '54321', 'personal', null),
  (gen_random_uuid(), 'ANA JULIA URIETA MARTINEZ', 'ana.urieta', '54321', 'personal', null),
  (gen_random_uuid(), 'ANA MARIA ARAUZ', 'ana.arauz', '54321', 'personal', null),
  (gen_random_uuid(), 'ANDREA BERMUDEZ CEVILLE', 'andrea.bermudez', '54321', 'personal', null),
  (gen_random_uuid(), 'ARIANNA QUIÑONES', 'arianna.quinones', '54321', 'personal', null),
  (gen_random_uuid(), 'ARICH NAYLA JIMENEZ MARTINEZ', 'arich.jimenez', '54321', 'personal', null),
  (gen_random_uuid(), 'ARMANDO CORREA ARROYO', 'armando.correa', '54321', 'personal', null),
  (gen_random_uuid(), 'ARNOLD NATHANIEL PERRY MARTINEZ', 'arnold.perry', '54321', 'personal', null),
  (gen_random_uuid(), 'ARNULFO MOJICA', 'arnulfo.mojica', '54321', 'personal', null),
  (gen_random_uuid(), 'BERTA GRACIELA NAVARRO', 'berta.navarro', '54321', 'personal', null),
  (gen_random_uuid(), 'BRANDO FULLER', 'brando.fuller', '54321', 'personal', null),
  (gen_random_uuid(), 'BRAULIO ORTEGA', 'braulio.ortega', '54321', 'personal', null),
  (gen_random_uuid(), 'CARLOS OCTAVIO VILLARREAL', 'carlos.villarreal', '54321', 'personal', null),
  (gen_random_uuid(), 'CARMEN LAFFAURIE', 'carmen.laffaurie', '54321', 'personal', null),
  (gen_random_uuid(), 'CECILIA MARIA HERNANDEZ CANTO', 'cecilia.hernandez', '54321', 'personal', null),
  (gen_random_uuid(), 'CLAUDIA LIZETH VALDERRAMA', 'claudia.valderrama', '54321', 'personal', null),
  (gen_random_uuid(), 'CRISTELL MILAGROS NISBETH AMARANTO', 'cristell.nisbeth', '54321', 'personal', null),
  (gen_random_uuid(), 'CRISTINA BRYAN', 'cristina.bryan', '54321', 'personal', null),
  (gen_random_uuid(), 'DAIZABET ALEZAIDA RIVERA VELASQUEZ', 'daizabet.rivera', '54321', 'personal', null),
  (gen_random_uuid(), 'DALMA GISELLA MONTERROZA VALLEJO', 'dalma.monterroza', '54321', 'personal', null),
  (gen_random_uuid(), 'DALYS LORENA RODRIGUEZ', 'dalys.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'DANIEL FERNANDO CHAVARRIA GUERRA', 'daniel.chavarria', '54321', 'personal', null),
  (gen_random_uuid(), 'DAVID LEONEL FALCON', 'david.falcon', '54321', 'personal', null),
  (gen_random_uuid(), 'DEBORA ESTHER JACKSON', 'debora.jackson', '54321', 'personal', null),
  (gen_random_uuid(), 'HUMBERTO JUNIOR ZAMORA', 'humberto.zamora', '54321', 'personal', null),
  (gen_random_uuid(), 'DINIA MARIBEL JARAMILLO', 'dinia.jaramillo', '54321', 'personal', null),
  (gen_random_uuid(), 'EIKYRA JAZMINE SANTOS ORTIZ', 'eikyra.santos', '54321', 'personal', null),
  (gen_random_uuid(), 'ELVIS RODRIGUEZ', 'elvis.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'EMELIN RAMIREZ PEREZ', 'emelin.ramirez', '54321', 'personal', null),
  (gen_random_uuid(), 'ENILCA EDITH ESPINOSA GRANT', 'enilca.espinosa', '54321', 'personal', null),
  (gen_random_uuid(), 'ERITA HERRERA MENDOZA', 'erita.herrera', '54321', 'personal', null),
  (gen_random_uuid(), 'ESQUIVEL GUEVARA VALENCIA', 'esquivel.guevara', '54321', 'personal', null),
  (gen_random_uuid(), 'EVELIN RUIZ', 'evelin.ruiz', '54321', 'personal', null),
  (gen_random_uuid(), 'FRANCISCO SAPENE', 'francisco.sapene', '54321', 'personal', null),
  (gen_random_uuid(), 'GENESIS  VARGAS', 'genesis.vargas', '54321', 'personal', null),
  (gen_random_uuid(), 'GLADYS MARGOTH ORTEGA MARTINEZ', 'gladys.ortega', '54321', 'personal', null),
  (gen_random_uuid(), 'HECTOR VILLARREAL', 'hector.villarreal', '54321', 'personal', null),
  (gen_random_uuid(), 'HORACIO ALBERTO MENDOZA VALLEJO', 'horacio.mendoza', '54321', 'personal', null),
  (gen_random_uuid(), 'INGRID JULISSA KAM MADRIGAL DE GONZALEZ', 'ingrid.kam', '54321', 'personal', null),
  (gen_random_uuid(), 'IRVING RAINIERO MELENDEZ PINEDA', 'irving.melendez', '54321', 'personal', null),
  (gen_random_uuid(), 'ISIS QUIROZ ORTEGA', 'isis.quiroz', '54321', 'personal', null),
  (gen_random_uuid(), 'JAVIER ENRIQUE IRIBARREN MORELLON', 'javier.iribarren', '54321', 'personal', null),
  (gen_random_uuid(), 'JEAN CARLOS NAVAS', 'jean.navas', '54321', 'personal', null),
  (gen_random_uuid(), 'JORGE ADMETH DE ROUX CANDANEDO', 'jorge.admethde', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSE FIERRO', 'jose.fierro', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSUE ABDIAS ARAUZ GONZALEZ', 'josue.arauz', '54321', 'personal', null),
  (gen_random_uuid(), 'JULIMETH DUQUE', 'julimeth.duque', '54321', 'personal', null),
  (gen_random_uuid(), 'JULIO CESAR JIMENEZ PUGA', 'julio.jimenez', '54321', 'personal', null),
  (gen_random_uuid(), 'KAREN RIVERA', 'karen.rivera', '54321', 'personal', null),
  (gen_random_uuid(), 'KATHERINE HON LIU', 'katherine.hon', '54321', 'personal', null),
  (gen_random_uuid(), 'KHADINE ALVARADO', 'khadine.alvarado', '54321', 'personal', null),
  (gen_random_uuid(), 'KIMBERLY JANISSE CAMPOS NAVARRO', 'kimberly.campos', '54321', 'personal', null),
  (gen_random_uuid(), 'LORELIZ DOMINGUEZ', 'loreliz.dominguez', '54321', 'personal', null),
  (gen_random_uuid(), 'LUCAS ALBERTO SANTOS MATEUS', 'lucas.santos', '54321', 'personal', null),
  (gen_random_uuid(), 'LUZ ENEIDA LOPEZ MONTERREY', 'luz.lopez', '54321', 'personal', null),
  (gen_random_uuid(), 'MADELAINE COSTA CAMARENA', 'madelaine.costa', '54321', 'personal', null),
  (gen_random_uuid(), 'MAGDALINE GONZALEZ', 'magdaline.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'MALEK ANGELICA EL HAMRA', 'malek.elhamra', '54321', 'personal', null),
  (gen_random_uuid(), 'MARCO ANTONIO OGILVIE', 'marco.ogilvie', '54321', 'personal', null),
  (gen_random_uuid(), 'MARIA SIMA', 'maria.sima', '54321', 'personal', null),
  (gen_random_uuid(), 'MARIA CRISTINA FONSECA', 'maria.cristina', '54321', 'personal', null),
  (gen_random_uuid(), 'MARIANELA FONSECA ZAUNER', 'marianela.fonseca', '54321', 'personal', null),
  (gen_random_uuid(), 'MONICA FUENTES GONZALEZ', 'monica.fuentes', '54321', 'personal', null),
  (gen_random_uuid(), 'NAKZEL EIXZA YEARWOOD MERCADO', 'nakzel.yearwood', '54321', 'personal', null),
  (gen_random_uuid(), 'NATCHIDEL MORAN', 'natchidel.moran', '54321', 'personal', null),
  (gen_random_uuid(), 'NILKA YPSILANTIS', 'nilka.ypsilantis', '54321', 'personal', null),
  (gen_random_uuid(), 'PAOLA ABDUL GONZALEZ', 'paola.abdul', '54321', 'personal', null),
  (gen_random_uuid(), 'PRISCILLA YANETH MORENO ESCUDERO', 'priscilla.moreno', '54321', 'personal', null),
  (gen_random_uuid(), 'THIAMA NASHUA GUN', 'thiama.gun', '54321', 'personal', null),
  (gen_random_uuid(), 'XIOMARA ALVARADO', 'xiomara.alvarado', '54321', 'personal', null),
  (gen_random_uuid(), 'MARITZA MOLINA', 'maritza.molina', '54321', 'personal', null),
  (gen_random_uuid(), 'YARA MORALES', 'yara.morales', '54321', 'personal', null),
  (gen_random_uuid(), 'YENI MERCEDES CASTILLO', 'yeni.castillo', '54321', 'personal', null),
  (gen_random_uuid(), 'YISSELLE EVELIA  ACOSTA', 'yisselle.acosta', '54321', 'personal', null),
  (gen_random_uuid(), 'YULENIS AIMEE BETEGON', 'yulenis.betegon', '54321', 'personal', null),
  (gen_random_uuid(), 'YULITZA GERTRUDIZ CAICEDO', 'yulitza.caicedo', '54321', 'personal', null),
  (gen_random_uuid(), 'ZULYRMA YANNYMAR RONDON', 'zulyrma.rondon', '54321', 'personal', null),
  (gen_random_uuid(), 'FREDD HINCAPIE', 'fredd.hincapie', '54321', 'personal', null),
  (gen_random_uuid(), 'IDALBIRIS ESTHER RENGIFO SILVA', 'idalbiris.rengifo', '54321', 'personal', null),
  (gen_random_uuid(), 'GENESIS GILL DIMAS', 'genesis.gill', '54321', 'personal', null),
  (gen_random_uuid(), 'ALEJANDRA GOMEZ', 'alejandra.gomez', '54321', 'personal', null),
  (gen_random_uuid(), 'ANDRES RODRIGUEZ', 'andres.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'ASTENIO ZAMORA HERRERA', 'astenio.zamora', '54321', 'personal', null),
  (gen_random_uuid(), 'CARLOS SANCHEZ', 'carlos.sanchez', '54321', 'personal', null),
  (gen_random_uuid(), 'CLARA INES PEREZ', 'clara.perez', '54321', 'personal', null),
  (gen_random_uuid(), 'DIANA CAROLINA FRANCO BONILLA', 'diana.franco', '54321', 'personal', null),
  (gen_random_uuid(), 'DESYLITH QUINTERO', 'desylith.quintero', '54321', 'personal', null),
  (gen_random_uuid(), 'ERIC ALBERTO PINTO RAMEA', 'eric.pinto', '54321', 'personal', null),
  (gen_random_uuid(), 'ERIKA SANCHEZ', 'erika.sanchez', '54321', 'personal', null),
  (gen_random_uuid(), 'GABRIELA ALFONSO NUÑEZ', 'gabriela.alfonso', '54321', 'personal', null),
  (gen_random_uuid(), 'GIANNI ANAIS PEREZ NUÑEZ', 'gianni.perez', '54321', 'personal', null),
  (gen_random_uuid(), 'HILLARY ASHLEY VILLARREAL', 'hillary.villarreal', '54321', 'personal', null),
  (gen_random_uuid(), 'ISAAC RODRIGUEZ', 'isaac.rodriguez', '54321', 'personal', null),
  (gen_random_uuid(), 'JAIME ALBERTO LASSO SANCHEZ', 'jaime.lasso', '54321', 'personal', null),
  (gen_random_uuid(), 'JESUS MANUEL UREÑA', 'jesus.urena', '54321', 'personal', null),
  (gen_random_uuid(), 'JOSE PABLO MUÑOZ', 'jose.munoz', '54321', 'personal', null),
  (gen_random_uuid(), 'JUANA VALENCIA', 'juana.valencia', '54321', 'personal', null),
  (gen_random_uuid(), 'KARLA DIAMANTE HO SANG', 'karla.hosang', '54321', 'personal', null),
  (gen_random_uuid(), 'KERIMA CORONADO', 'kerima.coronado', '54321', 'personal', null),
  (gen_random_uuid(), 'LEIDYS JOHANA CABALLERO MENDOZA', 'leidys.caballero', '54321', 'personal', null),
  (gen_random_uuid(), 'MAILYN MUÑOZ', 'mailyn.munoz', '54321', 'personal', null),
  (gen_random_uuid(), 'MILENA QUINTERO', 'milena.quintero', '54321', 'personal', null),
  (gen_random_uuid(), 'MONICA CEDEÑO', 'monica.cedeno', '54321', 'personal', null),
  (gen_random_uuid(), 'MONICA PAMELA DIAZ', 'monica.diaz', '54321', 'personal', null),
  (gen_random_uuid(), 'NATALIA DE LA CRUZ', 'natalia.dela', '54321', 'personal', null),
  (gen_random_uuid(), 'RAUL SANTIAGO TAPIA', 'raul.santiago', '54321', 'personal', null),
  (gen_random_uuid(), 'RICARDO JOSE PAREDES SOSA', 'ricardo.paredes', '54321', 'personal', null),
  (gen_random_uuid(), 'RUBIELA URRIOLA', 'rubiela.urriola', '54321', 'personal', null),
  (gen_random_uuid(), 'SERGIO MORAN', 'sergio.moran', '54321', 'personal', null),
  (gen_random_uuid(), 'SHEYSELL JARAMILLO', 'sheysell.jaramillo', '54321', 'personal', null),
  (gen_random_uuid(), 'SUYEN ESCOBAR', 'suyen.escobar', '54321', 'personal', null),
  (gen_random_uuid(), 'VIRGILIO TENORIO PASCACIO', 'virgilio.tenorio', '54321', 'personal', null),
  (gen_random_uuid(), 'YARELIS LINETH SOLIS ZAMBRANO', 'yarelis.solis', '54321', 'personal', null),
  (gen_random_uuid(), 'YARELYS CABALLERO', 'yarelys.caballero', '54321', 'personal', null),
  (gen_random_uuid(), 'YASIVEL SUGEI AROSEMENA RECUERO', 'yasivel.arosemena', '54321', 'personal', null),
  (gen_random_uuid(), 'YESICA GONZALEZ', 'yesica.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'YULISSA YANELIS GONZALEZ MARTINEZ', 'yulissa.gonzalez', '54321', 'personal', null),
  (gen_random_uuid(), 'ZELIBETH RAMSAY LINARES', 'zelibeth.ramsay', '54321', 'personal', null),
  (gen_random_uuid(), 'KATHERINE BERRIOS', 'katherine.berrios', '54321', 'personal', null),
  (gen_random_uuid(), 'MELANY ORTIZ LASHELY', 'melany.ortiz', '54321', 'personal', null),
  (gen_random_uuid(), 'CARMEN IVETTE CORDOBA ORTEGA', 'carmen.cordoba', '54321', 'personal', null),
  (gen_random_uuid(), 'JESSICA REAL BATISTA', 'jessica.real', '54321', 'personal', null),
  (gen_random_uuid(), 'ROLANDO GAMBOA SANCHEZ', 'rolando.gamboa', '54321', 'personal', null),
  (gen_random_uuid(), 'MATHIAS THOMAS GUICHARD', 'mathias.thomas', '54321', 'personal', null),
  (gen_random_uuid(), 'PAOLA ALESSANDRA ALVAREZ', 'paola.alessandra', '54321', 'personal', null),
  (gen_random_uuid(), 'TANIA LISBETH VEGA CASTRO', 'tania.vega', '54321', 'personal', null),
  (gen_random_uuid(), 'BEY MARIO DE LA GUARDIA', 'bey.mariode', '54321', 'personal', null),
  (gen_random_uuid(), 'VALERIN PÉREZ', 'valerin.perez', '54321', 'personal', null),
  (gen_random_uuid(), 'RAQUEL SANCHEZ', 'raquel.sanchez', '54321', 'personal', null),
  (gen_random_uuid(), 'KILEY HEROLD', 'kiley.herold', '54321', 'personal', null),
  (gen_random_uuid(), 'Asistente RRHH', 'asistente.rrhh', 'GLP2026', 'admin', null)
on conflict (usuario) do nothing;