[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/Obras y Proyectos/control-obras.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/Vacation System/vacation_system.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/Obras y Proyectos/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
